spring:
  application:
    name: main-server
  config:
    import: optional:file:.env[.properties]

maechuri:
  jwt:
    public-key-path: ${JWT_PUBLIC_KEY_PATH}
    private-key-path: ${JWT_PRIVATE_KEY_PATH}

minio:
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  bucket-name: ${MINIO_BUCKET_NAME:maechuri-bucket}
  region: ${MINIO_REGION:us-east-1}
